# Permalinks
permalink:        pretty

# Setup
title:            XbuntOS
tagline:          'Это всё. что нужно взять с собой...'
paginate:         10
paginate_path:    "page:num"
highlighter:      rouge
future:           true
show_drafts:      true

url:              https://whitepingvin.github.io/xbuntos/
shorturl:         whitepingvin.github.io/xbuntos

author:
  name:           Vicktor Suver
  url:            whitepingvin.ru

# This is the list of pages to include in the header of the website.
pages_list:
  О блоге: '/about'
  Архив записей: '/archive'
  Лента: '/atom.xml'

gems:
  - jemoji
  - jekyll-paginate
  - jekyll-gist
